options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args:
    - -c
    - |
      docker build -t southamerica-east1-docker.pkg.dev/microservicios-450921/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/microservicios-450921/image-registry/orders-ms",
      ]

availableSecrets:
  secretManager:
  - versionName: projects/158010496672/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'